version: '3.8'
services:
  tasks:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8001:8001
    volumes:
      - .:/data
    depends_on:
      - pgsql

  pgsql:
    image: postgres:16.2-alpine3.19
    restart: always
    env_file:
      - .env
    volumes:
      - .pgsql:/var/lib/pgsql