version: '3.0'

services:
  task:
    image: tasks-tasks:latest
    build: 
      context: .
    ports:
      - 8001:8001
    volumes:
      - ./data/web/static:/data/web/static/
    env_file:
      - ./.env
    depends_on:
      - postgres
  postgres:
    image: postgres:16.2-alpine3.19
    env_file:
      - ./.env
    expose:
      - 5432
    ports:
      - 5432:5432
  