version: '3.8'

services:
  tasks:
    image: tasks-tasks:latest
    build:
      context: .
    ports:
      - 8001:8001
    volumes:
      - ./tasks:/tasks
      - ./data/web/static:/data/web/static/
    depends_on:
      - pgsql
    env_file:
      - ./.env
  pgsql:
    image: postgres:16.2-alpine3.19
    env_file:
      - ./dotenv_files/.env
    volumes:
      - .pgsql:/var/lib/pgsql