version: '3.8'

services:
  app:
    image: users-user:latest
    build: 
      context: .
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mongo
    env_file:
      - ./.env

  mongo:
    image: mongo:8.0.0-rc13-jammy
    env_file:
      - ./.env

  mongo-express:
    image: mongo-express:1.0.2-20-alpine3.19
    restart: always
    ports:
      - 8081:8081
    depends_on:
      - mongo
