version: '3.8'
services:
  tasks:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8002:8002
    volumes:
      - .:/data
    depends_on:
      - mongo

  mongo:
    image: mongo:8.0.0-rc13-jammy
    restart: always
    env_file:
      - .env
    volumes:
      - .mongo:/var/lib/mongodb

  mongo-express:
    image: mongo-express:1.0.2-20-alpine3.19
    restart: always
    ports:
      - 8081:8081
    env_file:
      - .env