frontend:
  name: frontend-deploy
  image: gabrielnathan/frontend
  namespace: frontend
  tag: 1.0.5
  service: NodePort
  replicas: 1


mongodb:
  name: mongo
  image: mongo
  tag: 8.0.0-rc13-jammy
  port: 27017
  targetPort: 27017

pgsqldb:
  name: pgsql
  image: postgres
  tag: 16.2-alpine3.19
  port: 5432
  targetPort: 5432

mysqldb:
  name: mysql
  image: mysql
  tag: lts
  port: 3306
  targetPort: 3306

djangomysql:
  name: django-mysql
  image: gabrielnathan/projects
  tag: 1.0.6

djangopgsql:
  name: django-pgsql
  image: gabrielnathan/tasks
  tag: 1.0.5

nodejs:
  name: nodejs
  image: gabrielnathan/users
  tag: 1.0.7

service:
  type: ClusterIP

replicas: 1

secrets:
  url_users: aHR0cHM6Ly90Y2MuMTkyLjE2OC40OS4yLm5pcC5pby91c2Vycw==
  url_projects: aHR0cHM6Ly90Y2MuMTkyLjE2OC40OS4yLm5pcC5pbw==
  url_tasks: aHR0cHM6Ly90Y2MuMTkyLjE2OC40OS4yLm5pcC5pby90YXNrcy8=
  url_ai: aHR0cHM6Ly90Y2MuMTkyLjE2OC40OS4yLm5pcC5pby9haS8=
  
  mongodb_port: MjcwMTc=
  jwt_secret: MmRzamtkYXMwOWRzYTkwZGFqa2FzZGFta3NAISQlJWFkMDk4OW5rLTIzJCQhQA==
  
  pgsql_db: cG9zdGdyZXM=
  pgsql_user: cG9zdGdyZXM=
  pgsql_password: cG9zdGdyZXM=
  
  mysql_root_password: cGFzc3dvcmQ=
  mysql_user: Z2FicmllbA==
  mysql_user_password: Z2FicmllbDEyMw==
  mysql_db: cHJvamVjdHNfa2FuYmFu

  cors_allowed_origins: aHR0cDovLzE5Mi4xNjguNDkuMjozMDA4MA==
  django_engine_pgsql: ZGphbmdvLmRiLmJhY2tlbmRzLnBvc3RncmVzcWw=
  django_port_pgsql: NTQzMg==
  django_secret_key_pgsql: ZGphbmdvLWluc2VjdXJlLW0ocW1yZTVnJDBvbiVzNW5fdmFeODBnZXFnMmE0d14kMl9vKngwKjhiZXd5d0BkeC0t
  django_debug_pgsql: MQ==
  django_allowed_hosts_pgsql: dGNjLjE5Mi4xNjguNDkuMi5uaXAuaW8=
  
  open_ai_model: Z3B0LTRvLW1pbmk=
  open_ai_key: c2stcHJvai1QemFTSjRYR0hCUFhDZFFvcUczelQzQmxia0ZKbDNtWHBLWTFydkNXRWI0SUlTUEg=
  
  django_engine_mysql: ZGphbmdvLmRiLmJhY2tlbmRzLm15c3Fs
  django_port_mysql: MzMwNg==
  django_secret_key_mysql: ZGphbmdvLWluc2VjdXJlLW0ocW1yZTVnJDBvbiVzNW5fdmFeODBnZXFnMmE0d14kMl9vKngwKjhiZXd5d0BkeC0t
  django_debug_mysql: MQ==
  django_allowed_hosts_mysql: dGNjLjE5Mi4xNjguNDkuMi5uaXAuaW8=

volumes:
  names: 
    volume_mysql: mysql-storage
    volume_pgsql: pgsql-storage
    volume_mongo: mongo-storage
  storage: 1Mi