apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-django-pgsql-deploy
  labels:
    app: {{ .Values.djangopgsql.name }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.djangopgsql.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.djangopgsql.name }}
    spec:
      containers:
      - name: {{ .Values.djangopgsql.name }}
        image: {{ .Values.djangopgsql.image }}:{{ .Values.djangopgsql.tag }}
        ports:
        - containerPort: 8001
        env:
        - name: DB_ENGINE
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-secrets
              key: DB_ENGINE_DJANGO_PGSQL
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-secrets
              key: POSTGRES_DB
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-secrets
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-secrets
              key: POSTGRES_PASSWORD
        - name: POSTGRES_HOST
          value: {{ .Release.Name }}-pgsql-service
        - name: POSTGRES_PORT
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-secrets
              key: DJANGO_PORT_PGSQL
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-secrets
              key: DJANGO_SECRET_KEY_PGSQL
        - name: DEBUG
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-secrets
              key: DJANGO_DEBUB_PGSQL
        - name: ALLOWED_HOSTS
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-secrets
              key: DJANGO_ALLOWED_HOST_PGSQL
        - name: CORS_ALLOWED_ORIGINS
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-secrets
              key: CORS_ALLOWED_ORIGINS
        - name: OPEN_AI_MODEL
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-secrets
              key: OPEN_AI_MODEL  
        - name: OPEN_AI_KEY
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-secrets
              key: OPEN_AI_KEY  
              
        
        

             
    



