apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-mongodb-deploy
  labels:
    app: {{ .Values.mongodb.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.mongodb.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.mongodb.name }}
    spec:
      containers:
      - name: {{ .Values.mongodb.name }}
        image: {{ .Values.mongodb.image }}:{{ .Values.mongodb.tag }}
        ports:
        - containerPort: {{ .Values.mongodb.port }}
        volumeMounts:
        - name: {{ .Values.volumes.names.volume_mongo }}
          mountPath: /var/lib/mongo
      volumes:
      - name: {{ .Values.volumes.names.volume_mongo }}
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-mongo-volume-claim