# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: {{ .Release.Name }}-mongo-deploy
#   labels:
#     app: {{ .Values.mongodb.name }}
# spec:
#   replicas: {{ .Values.replicas }}
#   selector:
#     matchLabels:
#       app: {{ .Values.mongodb.name }}
#   template:
#     metadata:
#       labels:
#         app: {{ .Values.mongodb.name }}
#     spec:
#       containers:
#       - name: {{ .Values.mongodb.name }}
#         image: {{ .Values.mongodb.image }}:{{ .Values.mongodb.tag }}
#         ports:
#         - containerPort: {{ .Values.mongodb.port }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-mongodb-deploy
  labels:
    app: {{ .Values.mongodb.name }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.mongodb.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.mongodb.name }}
    spec:
      containers:
      - name: {{ .Values.mongodb.name }}
        image: {{ .Values.mongodb.image }}:{{ .Values.mongodb.tag }}
        ports:
        - containerPort: {{ .Values.mongodb.port }}