apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-nodejs-deploy
  labels:
    app: {{ .Values.nodejs.name }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.nodejs.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.nodejs.name }}
    spec:
      containers:
      - name: {{ .Values.nodejs.name }}
        image: {{ .Values.nodejs.image }}:{{ .Values.nodejs.tag }}
        ports:
        - containerPort: 3000
        env:
        - name: ME_CONFIG_MONGODB_URL
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-secrets
              key: ME_CONFIG_MONGODB_URL
        - name: MONGO_DB_PORT
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-secrets
              key: MONGO_DB_PORT
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-secrets
              key: JWT_SECRET

