apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-pgsql-deploy
  labels:
    app: {{ .Values.pgsqldb.name }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.pgsqldb.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.pgsqldb.name }}
    spec:
      containers:
      - name: {{ .Values.pgsqldb.name }}
        image: {{ .Values.pgsqldb.image }}:{{ .Values.pgsqldb.tag }}
        ports:
        - containerPort: {{ .Values.pgsqldb.port }}
        env:
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-secrets
              key: POSTGRES_DB
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-secrets
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-secrets
              key: POSTGRES_PASSWORD
        volumeMounts:
        - name: {{ .Values.volumes.names.volume_pgsql }}
          mountPath: /var/lib/pgsql
      volumes:
      - name: {{ .Values.volumes.names.volume_pgsql }}
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-pgsql-volume-claim