apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
type: Opaque
data:
  REACT_APP_URL_SERVE_USER: {{ .Values.secrets.url_users }}
  REACT_APP_URL_SERVE_PROJECTS: {{ .Values.secrets.url_projects }}
  REACT_APP_URL_SERVE_TASKS: {{ .Values.secrets.url_tasks }}
  REACT_APP_URL_SERVE_TASKS_AI: {{ .Values.secrets.url_ai }}
  
  MONGO_DB_PORT: {{ .Values.secrets.mongodb_port }}
  JWT_SECRET: {{ .Values.secrets.jwt_secret }}
  
  POSTGRES_DB: {{ .Values.secrets.pgsql_db }}
  POSTGRES_USER: {{ .Values.secrets.pgsql_user }}
  POSTGRES_PASSWORD: {{ .Values.secrets.pgsql_password }}
  
  CORS_ALLOWED_ORIGINS: {{ .Values.secrets.cors_allowed_origins }}
  OPEN_AI_MODEL: {{ .Values.secrets.open_ai_model }}
  OPEN_AI_KEY: {{ .Values.secrets.open_ai_key }}
  
  MYSQL_ROOT_PASSWORD: {{ .Values.secrets.mysql_root_password }}
  MYSQL_USER: {{ .Values.secrets.mysql_user }}
  MYSQL_PASSWORD: {{ .Values.secrets.mysql_user_password }}
  MYSQL_DATABASE: {{ .Values.secrets.mysql_db }}
  
  DB_ENGINE_DJANGO_PGSQL: {{ .Values.secrets.django_engine_pgsql }}
  DJANGO_PORT_PGSQL: {{ .Values.secrets.django_port_pgsql }}
  DJANGO_SECRET_KEY_PGSQL: {{ .Values.secrets.django_secret_key_pgsql }}
  DJANGO_DEBUB_PGSQL: {{ .Values.secrets.django_debug_pgsql }}
  DJANGO_ALLOWED_HOST_PGSQL: {{ .Values.secrets.django_allowed_hosts_pgsql }}
  
  DB_ENGINE_DJANGO_MYSQL: {{ .Values.secrets.django_engine_mysql }}
  DJANGO_PORT_MYSQL: {{ .Values.secrets.django_port_mysql }}
  DJANGO_SECRET_KEY_MYSQL: {{ .Values.secrets.django_secret_key_mysql }}
  DJANGO_DEBUB_MYSQL: {{ .Values.secrets.django_debug_mysql }}
  DJANGO_ALLOWED_HOST_MYSQL: {{ .Values.secrets.django_allowed_hosts_mysql }}
