apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-django-psql-service
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Values.djangopgsql.name }}
  ports:
  - port: 80
    targetPort: 8001
