apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-nodejs-service
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Values.nodejs.name }}
  ports:
  - port: 80
    targetPort: 3000