apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-pgsql-service
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Values.pgsqldb.name }}
  ports:
  - port: {{ .Values.pgsqldb.port }}
    targetPort: {{ .Values.pgsqldb.targetPort }}