apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-django-mysql-service
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Values.djangomysql.name }}
  ports:
  - port: {{ .Values.djangomysql.port }}
    targetPort: {{ .Values.djangomysql.targetPort }}
