version: '3.8'
services:
  project:
    image: projects-project:latest
    build:
      context: .
    ports:
      - 8000:8000
    volumes:
      - ./project:/project
      - ./data/web/static:/data/web/static/
    depends_on:
      - mysql
    env_file:
      - ./dotenv_files/.env

  mysql:
    image: mysql:lts
    env_file:
      - ./dotenv_files/.env
    volumes:
      - .mysql:/var/lib/mysql