version: '3.8'
services:
  project:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - .:/data
    depends_on:
      - mysql

  mysql:
    image: mysql:lts
    restart: always
    env_file:
      - .env
    volumes:
      - .mysqldata:/var/lib/mysql