name: CI/CD with Minikube and Helm

on:
  push:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: start minikube
        id: minikube
        uses: medyagh/setup-minikube@latest
      - name: Set up Helm
        uses: azure/setup-helm@v4.2.0
        with:
          version: v3.14.4
      - name: Install cert-manager
        run: |
          kubectl apply --validate=false -f https://github.com/cert-manager/cert-manager/releases/download/v1.12.5/cert-manager.crds.yaml
          helm repo add jetstack https://charts.jetstack.io
          helm repo update
          helm install cert-manager jetstack/cert-manager --namespace cert-manager --create-namespace --version v1.12.5
          kubectl wait --namespace cert-manager --for=condition=available deployment/cert-manager --timeout=120s

  deploy:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Deploy with Helm
        run: |
          helm upgrade --install demo ./k8s --wait
          helm list

      - name: Run Tests
        run: |
          minikube addons enable ingress 
          kubectl get all
          kubectl get ingress
